openapi: 3.0.3
info:
  title: Mixing API
  version: 0.1.0
  description: API for real-time DJ mixing and remix generation

paths:
  /mixing/sessions:
    post:
      summary: Create a new mixing session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                deck_a_song_id:
                  type: string
                  format: uuid
                deck_b_song_id:
                  type: string
                  format: uuid
                  nullable: true
                user_id:
                  type: string
                  format: uuid
              required:
                - deck_a_song_id
      responses:
        '201':
          description: Mixing session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MixSession'
        '400':
          description: Invalid song IDs

    get:
      summary: List active mixing sessions for user
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of active sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MixSession'

  /mixing/sessions/{session_id}:
    get:
      summary: Get mixing session details
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MixSessionDetail'
        '404':
          description: Session not found

    put:
      summary: Update mixing session state
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MixSessionUpdate'
      responses:
        '200':
          description: Session updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MixSession'
        '404':
          description: Session not found

    delete:
      summary: End mixing session
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Session ended
        '404':
          description: Session not found

  /mixing/sessions/{session_id}/cue-points:
    get:
      summary: Get AI-detected cue points for current tracks
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Cue points for both decks
          content:
            application/json:
              schema:
                type: object
                properties:
                  deck_a_cue_points:
                    type: array
                    items:
                      $ref: '#/components/schemas/CuePoint'
                  deck_b_cue_points:
                    type: array
                    items:
                      $ref: '#/components/schemas/CuePoint'

  /mixing/sessions/{session_id}/auto-mix:
    post:
      summary: Generate automatic mix between current tracks
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mix_style:
                  type: string
                  enum: [seamless, energy_build, quick_cut, creative]
                  default: seamless
                duration:
                  type: number
                  minimum: 5
                  maximum: 60
                  default: 16
                  description: Mix duration in seconds
      responses:
        '200':
          description: Auto-mix parameters generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AutoMixResult'

  /mixing/remix:
    post:
      summary: Generate remix by swapping compatible stems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                base_song_id:
                  type: string
                  format: uuid
                stem_swaps:
                  type: array
                  items:
                    type: object
                    properties:
                      source_song_id:
                        type: string
                        format: uuid
                      stem_type:
                        type: string
                        enum: [vocals, drums, bass, other, harmony]
                      time_stretch:
                        type: boolean
                        default: true
                      pitch_shift:
                        type: boolean
                        default: true
                output_format:
                  type: string
                  enum: [wav, mp3]
                  default: wav
              required:
                - base_song_id
                - stem_swaps
      responses:
        '202':
          description: Remix generation started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemixJob'
        '400':
          description: Invalid stem swap configuration

  /mixing/remix/{job_id}:
    get:
      summary: Get remix generation status
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Remix job status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RemixJob'
        '404':
          description: Job not found

  /mixing/waveform/{song_id}:
    get:
      summary: Get waveform data for visualization
      parameters:
        - name: song_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: resolution
          in: query
          schema:
            type: integer
            minimum: 100
            maximum: 10000
            default: 1000
            description: Number of waveform points
        - name: stem_type
          in: query
          schema:
            type: string
            enum: [master, vocals, drums, bass, other]
            default: master
      responses:
        '200':
          description: Waveform data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WaveformData'

components:
  schemas:
    MixSession:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        deck_a_song_id:
          type: string
          format: uuid
        deck_b_song_id:
          type: string
          format: uuid
          nullable: true
        crossfader_position:
          type: number
          minimum: -1
          maximum: 1
          description: -1 = full deck A, 1 = full deck B
        deck_a_cue_time:
          type: number
          description: Current position on deck A (seconds)
        deck_b_cue_time:
          type: number
          description: Current position on deck B (seconds)
        session_timestamp:
          type: string
          format: date-time
        is_active:
          type: boolean

    MixSessionDetail:
      allOf:
        - $ref: '#/components/schemas/MixSession'
        - type: object
          properties:
            deck_a_song:
              $ref: '#/components/schemas/Song'
            deck_b_song:
              $ref: '#/components/schemas/Song'
            mix_parameters:
              $ref: '#/components/schemas/MixParameters'

    MixSessionUpdate:
      type: object
      properties:
        crossfader_position:
          type: number
          minimum: -1
          maximum: 1
        deck_a_cue_time:
          type: number
        deck_b_cue_time:
          type: number
        deck_b_song_id:
          type: string
          format: uuid
        mix_parameters:
          $ref: '#/components/schemas/MixParameters'

    MixParameters:
      type: object
      properties:
        deck_a_eq:
          $ref: '#/components/schemas/EQSettings'
        deck_b_eq:
          $ref: '#/components/schemas/EQSettings'
        deck_a_gain:
          type: number
          minimum: 0
          maximum: 2
        deck_b_gain:
          type: number
          minimum: 0
          maximum: 2
        deck_a_effects:
          type: array
          items:
            $ref: '#/components/schemas/Effect'
        deck_b_effects:
          type: array
          items:
            $ref: '#/components/schemas/Effect'

    EQSettings:
      type: object
      properties:
        bass:
          type: number
          minimum: -12
          maximum: 12
          description: Bass adjustment in dB
        mid:
          type: number
          minimum: -12
          maximum: 12
          description: Mid adjustment in dB
        treble:
          type: number
          minimum: -12
          maximum: 12
          description: Treble adjustment in dB

    Effect:
      type: object
      properties:
        type:
          type: string
          enum: [reverb, delay, filter, phaser, chorus, distortion]
        enabled:
          type: boolean
        parameters:
          type: object
          description: Effect-specific parameters

    CuePoint:
      type: object
      properties:
        time:
          type: number
          description: Time position in seconds
        type:
          type: string
          enum: [intro_start, verse_start, chorus_start, breakdown, buildup, drop, outro_start]
        confidence:
          type: number
          minimum: 0
          maximum: 1
          description: AI confidence in this cue point
        energy_level:
          type: number
          minimum: 0
          maximum: 1
          description: Energy level at this point

    AutoMixResult:
      type: object
      properties:
        transition_start_time:
          type: number
          description: When to start transition on current track
        transition_end_time:
          type: number
          description: When transition completes on next track
        crossfade_curve:
          type: array
          items:
            type: object
            properties:
              time:
                type: number
              deck_a_volume:
                type: number
                minimum: 0
                maximum: 1
              deck_b_volume:
                type: number
                minimum: 0
                maximum: 1
        eq_automation:
          type: array
          items:
            type: object
            properties:
              time:
                type: number
              deck_a_eq:
                $ref: '#/components/schemas/EQSettings'
              deck_b_eq:
                $ref: '#/components/schemas/EQSettings'
        effects_automation:
          type: array
          items:
            type: object
            properties:
              time:
                type: number
              deck:
                type: string
                enum: [a, b]
              effect:
                $ref: '#/components/schemas/Effect'

    RemixJob:
      type: object
      properties:
        id:
          type: string
          format: uuid
        status:
          type: string
          enum: [pending, processing, completed, failed]
        progress:
          type: number
          minimum: 0
          maximum: 100
          description: Completion percentage
        base_song_id:
          type: string
          format: uuid
        stem_swaps:
          type: array
          items:
            type: object
            properties:
              source_song_id:
                type: string
                format: uuid
              stem_type:
                type: string
                enum: [vocals, drums, bass, other, harmony]
        output_file_path:
          type: string
          nullable: true
          description: Path to generated remix file
        created_timestamp:
          type: string
          format: date-time
        completed_timestamp:
          type: string
          format: date-time
          nullable: true
        error_message:
          type: string
          nullable: true

    WaveformData:
      type: object
      properties:
        song_id:
          type: string
          format: uuid
        stem_type:
          type: string
          enum: [master, vocals, drums, bass, other]
        resolution:
          type: integer
          description: Number of data points
        duration:
          type: number
          description: Total duration in seconds
        sample_rate:
          type: integer
          description: Audio sample rate
        peaks:
          type: array
          items:
            type: number
            minimum: -1
            maximum: 1
          description: Waveform peak values
        rms:
          type: array
          items:
            type: number
            minimum: 0
            maximum: 1
          description: RMS energy values

    Song:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        artist:
          type: string
        duration:
          type: number